- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    - LIST
    - ansible
    - SHELL
  CONCEPT:
    SHELL: shell script
    KEY: "KEYS, ARE"
  types:
    - name: data
      ansible.builtin.debug:
        msg: "THE {{ vars }} AND {{ CONCEPT }}"
