- name: conditions
  hosts: local
  connection: local
  vars:
    NUMBER: 1
  tasks:
  - name: print number less than
    ansible.builtin.debug:
      msg: "the {{NUMBER}} is less than 11"
    when: NUMBER < 11

  - name: print number
    ansible.builtin.debug:
      msg: "the {{NUMBER}} is greater than 11"
    when: NUMBER > 11