- name: conditions
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: con
    ansible.builtin.package:
      name: nginx
      state: present
    when: ansible_os_family == "RedHat"

  - name: if con
    ansible.builtin.package:
      name: dabin
      state: present
    when: ansible_os_family == "Debian"