- name: loops
  hosts: frontend
  become: yes
  tasks:
  - name: loops in ansible
    ansible.builtin.debug:
      msg: "hello {{ item }}" #item here is reserved keyword
    loop:
    - SURESH
    - RAEMESH
    - KING