- name: functions
  hosts: local
  connection: local
  vars: 
    persons: "Suresh,Ravi,Raju"
  tasks:
  - name: hello function
    ansible.builtin.debug:
      msg: "HELLO , {{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "{{ persons }}"

  - name: unctionality
    ansible.builtin.debug:
      msg: "{{ persons | split(',') }}"

  - name: maps in to list
    vars:
      student:
        NAME: SAI
        ROLLNO: 9
        BRANCH: ECE
    ansible.builtin.debug:
      msg: "{{ student | dict2items }}"
      
  - name: lists into maps
    vars:
      students:
        - {'key': 'NAME' , 'value': 'SAI'}
        - {'key': 'ROLLNO' , 'value': '9'}
        - {'key': 'BRANCH', 'value': 'ECE'}
    ansible.builtin.debug:
      msg: "{{ students | items2dict }}"

  - name: convert to uppercase
    vars:
      name: "Sivakumar Reddy M"
    ansible.builtin.debug:
      msg: "Hello {{ name | upper }}"


