- name: functions
  hosts: local
  connection: local
  var: 
    person: "Suresh, Ramesh, Raju"
  tasks:
  - name: hello function
    ansible.builtin.debug:
      msg: "HELLO , {{ person | default('Ramesh') }}"

