- name: functions
  hosts: local
  connection: local
  vars: 
    person: "Suresh, Ramesh, Raju"
  tasks:
  - name: hello function
    ansible.builtin.debug:
      msg: "HELLO , {{ person | default('Ramesh') }}"
  - name: print names
    ansible.builtin.debug:
      msg: "{{ person}}"

