- name: functions
  hosts: local
  connection: local
  vars: 
    persons: "Suresh,Ravi,Raju"
  tasks:
  - name: hello function
    ansible.builtin.debug:
      msg: "HELLO , {{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "{{ persons }}"

  - name: unctionality
    ansible.builtin.debug:
      msg: "{{ persons | split(',') }}"

  - name: maps
    vars:
      student:
        NAME: SAI
        ROLLNO: 9
        BRANCH: ECE
    ansilble.builtin.debug:
      msg: "{{ student | dict2items }}"
      
