- name: functions
  hosts: local
  connection: local
  vars: 
    persons: "Suresh,Ravi,Raju"
  tasks:
  - name: hello function
    ansible.builtin.debug:
      msg: "HELLO , {{ person | default('Ramesh') }}"

  - name: print names
    ansible.builtin.debug:
      msg: "{{ persons }}"

  - name: split 
    ansible.built.debug:
      msg: "{{ person | split(',')}}"
