- name: nginx connection
  hosts: dynamic_frontend
  become: yes
  tasks:
    - name: nginx connection
      ansible.builtin.package:
        name: nginx
        state: present
        
    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes   
