- name: install and run nginx
  hosts: frontend
  become: yes  #sudo user
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.package:
      name: nginx
      state: started 
      enabled: yes