- name: prompt testing
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: ENTER YOUR USERNAME
    private: true
  
  - name: PASSWORD
    prompt: ENTER YOUR PASSWORD
    private: true
  tasks:
    - name: USERNAME and PASSWORD
      ansible.builtin.debug:
        msg: "THE {{USERNAME}} AND {{PASSWORD}}"