# - name: basic
#   hosts: frontend
#   tasks:
#     - name: ping the server
#       ansible.builtin.ping:

- name: printing hello
  hosts: frontend
  tasks:
    ansible.builtin.debug:
      msg: "hello world"
