# - name: basic
#   hosts: frontend
#   tasks:
#     - name: ping the server
#       ansible.builtin.ping:

# - name: printing
#   hosts: frontend
#   tasks:
#     - name: hello
#       ansible.builtin.debug:
#         msg: "hello world"

# - name: nginx
#   hosts: frontend
#   become: yes   
#   tasks:
#     - name: installing nginx
#       ansible.builtin.package:
#         name: nginx
#         state: present
#     - name: running nginx
#       ansible.builtin.service:
#         name: nginx
#         state: started
#         enabled: yes


# - name: play vars
#   hosts: frontend
#   vars:
#     COURSE: DEVOPS
#   vars_files:
#   - course.yaml
#   tasks:
#     - name: play vars in ansible
#       ansible.builtin.debug:
#         msg: "{{ COURSE }}"

#     - name: play tasks vars in ansible
#       vars:
#         COURSE: AWS
#       ansible.builtin.debug:
#         msg: "{{ COURSE }}"

#     - name: play file vars in ansible
#       ansible.builtin.debug:
#         msg: "{{ COURSE }}"

- name: prompt
  hosts: local
  connection: local
  vars_prompt:
    name: EMP
    prompt: "ENTER YOUR EMPID"
    private: true
  tasks:
    - name: printing
      ansible.builtin.debug:
        msg: "youe empid is {{ EMP }}"
    

