# - name: basic
#   hosts: frontend
#   tasks:
#     - name: ping the server
#       ansible.builtin.ping:

# - name: printing
#   hosts: frontend
#   tasks:
#     - name: hello
#       ansible.builtin.debug:
#         msg: "hello world"

# - name: nginx
#   hosts: frontend
#   become: yes   
#   tasks:
#     - name: installing nginx
#       ansible.builtin.package:
#         name: nginx
#         state: present
#     - name: running nginx
#       ansible.builtin.service:
#         name: nginx
#         state: started
#         enabled: yes


- name: play vars
  hosts: frontend
  vars:
    COURSE: DEVOPS
  tasks:
    ansible.builtin.debug:
      msg: "{{ COURSE }}"

